plugins {
    id 'application'
    id 'checkstyle'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.addAll(['-Xlint:all', '-Werror'])
}

checkstyle {
    toolVersion = '10.17.0'
    configFile = file("$rootDir/config/checkstyle/checkstyle.xml")
}

javafx {
    version = "21.0.2"
    modules = ['javafx.controls', 'javafx.graphics']
}

application {
    mainClass = 'dev.somgester.sylph.App'
}

tasks.named('test') {
    useJUnitPlatform()
}